use crate::CardGame::Player::Move;
use crate::CardGame::Card::Card;

pub enum Expr {
    Any(Box<Expr>),
    All(Box<Expr>),
    Greatest(Box<Expr>),
    Players(Box<Expr>),
    Score,
    Hand,
    IsEqual,
    Numeric(i32),
    IsEmpty(Box<Expr>),
    If(Vec<Expr>, Vec<Expr>),
    Swap(Box<Expr>, Box<Expr>),
    Shuffle(Box<Expr>),
    Deck,
    Pile,
    Discard,
    Take(Box<Expr>, Box<Expr>, Box<Expr>),
    Always,
    Never,
    Not(Vec<Expr>),
    And(Vec<Expr>, Vec<Expr>),
    Or(Vec<Expr>, Vec<Expr>),
    AffectPlayer(String, Option<Vec<Expr>>),
    TOLeft,
    TORight,
    CardRank,
    CardSuit,
    CardValue,
    PlayerAction(Move, bool),
    CurrentPlayer(Box<Expr>),
    PreviousPlayer(Box<Expr>),
    Reset(Box<Expr>),
    Cards(Vec<Card>),
    Turn,   
    GoBack(Box<Expr>),
    GoForward(Box<Expr>),
    IsMove(Box<Expr>),
    Move(Box<Expr>),
    IsSame(Box<Expr>, Box<Expr>),
    Look(Box<Expr>, Box<Expr>),
    Put(Box<Expr>, Box<Expr>),
    Text(String),
    CLe,
    CGr,
    CEq,
    CLEq,
    CGRq,
    Null
}